# Generated by Django 5.0.7 on 2024-12-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=64)),
                ('telefone', models.CharField(max_length=50)),
                ('cargo', models.CharField(choices=[('Admin', 'Administrador'), ('Comum', 'Comum')], default='Comum', max_length=18)),
            ],
        ),
    ]
